[build]
base = "exampleSite/"
publish = "public"
command = "hugo --gc --minify --themesDir ../ --layoutDir ../layouts --baseURL 'https://fly-out.netlify.com'"

[context.production.environment]
HUGO_VERSION = "0.65.2"

# [context.deploy-preview]
# command = "npm run build -- -b $DEPLOY_PRIME_URL --environment staging"
# [context.deploy-preview.environment]
# HUGO_VERSION = "0.65.2"

# [context.branch-deploy]
# command = "npm run build -- -b $DEPLOY_PRIME_URL"
# [context.branch-deploy.environment]
# HUGO_VERSION = "0.65.2"
