baseURL: "https://fly-out.netlify.com"
# theme: hugo-theme-iris

# googleAnalytics: UA-123-45
disqusShortname: hugothemeiris

# paginate: 3
canonifyURLs: true
enableRobotsTXT: true
pluralizeListTitles: false

# hugo syntax highlighting
pygmentsUseClasses: true
pygmentsCodefences: true

enableEmoji: true
enableGitInfo: true
enableInlineShortcodes: true

taxonomies: {}
#   - tag: tags

imaging:
  quality: 75

markup:
  goldmark:
    renderer:
      unsafe: true

# Configure Languages
DefaultContentLanguage: en
languages:
  en:
    contentDir: content/en
    languageName: English
    languageCode: en-us
    params:
      author: NagoDede
      description: Soft and Fly
      ogp:
        siteName: Fly-out
        image: images/ogp.jpg
        locale: en-US
    title: Fly-out
    weight: 1
  fr:
    contentDir: content/fr
    languageName: Français
    languageCode: fr-fr
    params:
      author: NagoDede
      description: 
      ogp:
        siteName: Fly-out
        image: images/ogp.jpg
        locale: fr-FR
    title: Fly-out
    weight: 2
